"""Constants for the Bilibili live adapter plugin."""

GATEWAY_NAME = "bilibili_live_gateway"
PLATFORM_NAME = "bilibili_live"
PROTOCOL_NAME = "bilibili_live_ws"
SUPPORTED_CONFIG_VERSION = "0.2.1"

DEFAULT_RECONNECT_DELAY_SEC = 5.0
DEFAULT_HEARTBEAT_INTERVAL_SEC = 30.0
DEFAULT_CONNECT_TIMEOUT_SEC = 10.0
DEFAULT_BILIBILI_WS_URL = "wss://broadcastlv.chat.bilibili.com/sub"
DEFAULT_VTS_WS_URL = "ws://127.0.0.1:8002"
DEFAULT_NAPCAT_CONTROL_API_NAME = "adapter.napcat.connection.set_enabled"

BILIBILI_OPERATION_HEARTBEAT = 2
BILIBILI_OPERATION_HEARTBEAT_REPLY = 3
BILIBILI_OPERATION_MESSAGE = 5
BILIBILI_OPERATION_AUTH = 7
BILIBILI_OPERATION_AUTH_REPLY = 8
BILIBILI_PROTOCOL_PLAIN = 0
BILIBILI_PROTOCOL_ZLIB = 2

LIVE2D_BRIDGE_SOURCE = "maibot_bilibili_live_adapter"
